/**
 * This class is generated by jOOQ
 */
package jooq.tables.records;


import javax.annotation.Generated;

import jooq.tables.Bucket;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BucketRecord extends UpdatableRecordImpl<BucketRecord> implements Record3<Long, String, Long> {

    private static final long serialVersionUID = -652644318;

    /**
     * Setter for <code>PUBLIC.BUCKET.BUCKETID</code>.
     */
    public void setBucketid(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.BUCKET.BUCKETID</code>.
     */
    public Long getBucketid() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>PUBLIC.BUCKET.BUCKETNAME</code>.
     */
    public void setBucketname(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.BUCKET.BUCKETNAME</code>.
     */
    public String getBucketname() {
        return (String) get(1);
    }

    /**
     * Setter for <code>PUBLIC.BUCKET.GADGETID</code>.
     */
    public void setGadgetid(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>PUBLIC.BUCKET.GADGETID</code>.
     */
    public Long getGadgetid() {
        return (Long) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Long, String, Long> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Long, String, Long> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Bucket.BUCKET.BUCKETID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Bucket.BUCKET.BUCKETNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return Bucket.BUCKET.GADGETID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getBucketid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getBucketname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getGadgetid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BucketRecord value1(Long value) {
        setBucketid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BucketRecord value2(String value) {
        setBucketname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BucketRecord value3(Long value) {
        setGadgetid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BucketRecord values(Long value1, String value2, Long value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BucketRecord
     */
    public BucketRecord() {
        super(Bucket.BUCKET);
    }

    /**
     * Create a detached, initialised BucketRecord
     */
    public BucketRecord(Long bucketid, String bucketname, Long gadgetid) {
        super(Bucket.BUCKET);

        set(0, bucketid);
        set(1, bucketname);
        set(2, gadgetid);
    }
}
