/**
 * This class is generated by jOOQ
 */
package jooq;


import javax.annotation.Generated;

import jooq.tables.Bucket;
import jooq.tables.Gadget;


/**
 * Convenience access to all tables in PUBLIC
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>PUBLIC.GADGET</code>.
     */
    public static final Gadget GADGET = jooq.tables.Gadget.GADGET;

    /**
     * The table <code>PUBLIC.BUCKET</code>.
     */
    public static final Bucket BUCKET = jooq.tables.Bucket.BUCKET;
}
